forceNamespace: ""
imagePullSecrets: []
serviceAccountName: tuf
roleName: tuf
roleBindingName: tuf
fullnameOverride: tuf
enabled: true

deployment:
  name: tuf
  replicas: 1
  registry: ghcr.io
  repository: sigstore/scaffolding/server
  # v0.7.8
  version: sha256:dfccfb85b8638b488a3fd2320d723efb37633be7c32c34a1ab58138e5f80d0e2
  imagePullPolicy: IfNotPresent
  port: 8080
  tolerations: []
  nodeSelector: {}
  affinity: {}

secrets:
  rekor:
    create: false
    enabled: true
    name: rekor-public-key
    key: key
    path: rekor.pub
  fulcio:
    create: false
    enabled: true
    name: fulcio-server-secret
    key: cert
    path: fulcio_v1.crt.pem
  ctlog:
    create: false
    enabled: true
    name: ctlog-public-key
    key: public
    path: ctfe.pub
  tsa:
    create: false
    enabled: true
    name: tsa-cert-chain
    key: cert-chain
    path: tsa.certchain.pem

ingress:
  create: true
  name: tuf-server
  className: nginx
  annotations: {}
  http:
    hosts:
    - path: /
      host: "tuf.localhost"

service:
  name: tuf-server
  port: 80

namespace:
  create: false
  name: fulcio-system
