namespace:
  create: false
  name: ctlog-system

imagePullSecrets: []

server:
  replicaCount: 1
  config:
    key: treeID
    treeID: ""
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/ct_server
    pullPolicy: IfNotPresent
    # v0.7.11
    version: sha256:d6238aba1c35d3a2aae832469b20618e19a638da5f70d37791d945ce010f2027
  livenessProbe:
    httpGet:
      path: /healthz
      port: 6962
    initialDelaySeconds: 10
  readinessProbe:
    httpGet:
      path: /healthz
      port: 6962
    initialDelaySeconds: 10
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: false
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "6963"
  portHTTP: 6962
  portHTTPMetrics: 6963
  service:
#    backendConfig:
#      name: ctlog-backend-config
#      spec: # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#configuring_ingress_features_through_backendconfig_parameters
#        securityPolicy:
#          name: ctlog-security-policy
#        logging:
#          enable: true
#        healthCheck:
#          port: 6962
#          requestPath: "/healthz"
#          type: HTTP
    type: ClusterIP
    ports:
      - name: 6962-tcp
        port: 80
        protocol: TCP
        targetPort: 6962
      - name: 6963-tcp
        port: 6963
        protocol: TCP
        targetPort: 6963
  ingress:
    enabled: false
    className: nginx
    hosts:
      - path: /
    annotations: {}
    tls: []
  ingresses:
    - enabled: false
      name: "gce-ingress"
      className: "gce"
      hosts:
        - host: fulcio.localhost
          paths:
            - path: /test
              pathType: Prefix
            - path: /other-shard
              serviceName: other-shard
      annotations: {}
      tls: []
      staticGlobalIP: lb-ext-ip
      frontendConfigSpec:   # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#configuring_ingress_features_through_frontendconfig_parameters
        sslPolicy: ctlog-ssl-policy
        redirectToHttps:
          enabled: true
  extraArgs: []
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
  tolerations: []
  nodeSelector: {}
  affinity: {}

createtree:
  enabled: true
  name: createtree
  # This must be < 20 characters
  displayName: ctlog-tree
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createtree
    pullPolicy: IfNotPresent
    # v0.7.11
    version: sha256:4e3614df07561b096f1bfe1e1f79582b1545d6253bfad0f79235a1a1af74ef03
  ttlSecondsAfterFinished: 3600
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
  annotations: {}
  tolerations: []
  nodeSelector: {}
  affinity: {}

createctconfig:
  enabled: true
  replicaCount: 1
  backoffLimit: 6
  name: createctconfig
  initContainerImage:
    curl:
      registry: docker.io
      repository: curlimages/curl
      # -- 8.10.1
      version: sha256:d9b4541e214bcd85196d6e92e2753ac6d0ea699f0af5741f8c6cccbfcf00ef4b
      imagePullPolicy: IfNotPresent
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createctconfig
    pullPolicy: IfNotPresent
    # -- v0.7.11
    version: sha256:bcab917a07bb27f847531b145679b4b9a57bcaa85bb91e0b441ae9473c24fb79
  fulcioURL: "http://fulcio-server.fulcio-system.svc"
  logPrefix: sigstorescaffolding
  privateKeyPasswordSecretName: ""
  ttlSecondsAfterFinished: 3600
  pubkeysecret: "ctlog-public-key"
  # If there's an existing private key that should be used for ctlog, specify
  # here. This is important if a key has been created and imported into TUF.
  privateSecret: ""
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
  annotations: {}
  tolerations: []
  nodeSelector: {}
  affinity: {}

trillian:
  namespace: trillian-system
  logServer:
    name: trillian-logserver
    portRPC: 8091

# Force namespace of namespaced resources
forceNamespace: ""
