namespace:
  create: false
  name: ctlog-system

imagePullSecrets: []

server:
  replicaCount: 1
  config:
    key: treeID
    treeID: ""
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/ct_server
    pullPolicy: IfNotPresent
    # v0.7.8
    version: sha256:60f76cc090a18f278b2e8cdd1f8901543455a8a6f3c3bcd7a4a3f1481534552a
  livenessProbe:
    httpGet:
      path: /healthz
      port: 6962
    initialDelaySeconds: 10
  readinessProbe:
    httpGet:
      path: /healthz
      port: 6962
    initialDelaySeconds: 10
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: false
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "6963"
  portHTTP: 6962
  portHTTPMetrics: 6963
  service:
#    backendConfig:
#      name: ctlog-backend-config
#      spec: # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#configuring_ingress_features_through_backendconfig_parameters
#        securityPolicy:
#          name: ctlog-security-policy
#        logging:
#          enable: true
#        healthCheck:
#          port: 6962
#          requestPath: "/healthz"
#          type: HTTP
    type: ClusterIP
    ports:
      - name: 6962-tcp
        port: 80
        protocol: TCP
        targetPort: 6962
      - name: 6963-tcp
        port: 6963
        protocol: TCP
        targetPort: 6963
  ingress:
    enabled: false
    className: nginx
    hosts:
      - path: /
    annotations: {}
    tls: []
  ingresses:
    - enabled: false
      name: "gce-ingress"
      className: "gce"
      hosts:
        - host: fulcio.localhost
          paths:
            - path: /test
              pathType: Prefix
            - path: /other-shard
              serviceName: other-shard
      annotations: {}
      tls: []
      staticGlobalIP: lb-ext-ip
      frontendConfigSpec:   # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#configuring_ingress_features_through_frontendconfig_parameters
        sslPolicy: ctlog-ssl-policy
        redirectToHttps:
          enabled: true
  extraArgs: []
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
  tolerations: []
  nodeSelector: {}
  affinity: {}

createtree:
  enabled: true
  name: createtree
  # This must be < 20 characters
  displayName: ctlog-tree
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createtree
    pullPolicy: IfNotPresent
    # v0.7.8
    version: sha256:c0cc90af73b71eaf0835c332d99834b669a36698c44c454835589bbc5acac478
  ttlSecondsAfterFinished: 3600
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
  annotations: {}
  tolerations: []
  nodeSelector: {}
  affinity: {}

createctconfig:
  enabled: true
  replicaCount: 1
  backoffLimit: 6
  name: createctconfig
  initContainerImage:
    curl:
      registry: docker.io
      repository: curlimages/curl
      # -- 8.9.1
      version: sha256:8addc281f0ea517409209f76832b6ddc2cabc3264feb1ebbec2a2521ffad24e4
      imagePullPolicy: IfNotPresent
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createctconfig
    pullPolicy: IfNotPresent
    # -- v0.7.8
    version: sha256:d72a616f53005c51dd0f3fa40848e5149d23fb1c3dd216525f54d54dcca36b49
  fulcioURL: "http://fulcio-server.fulcio-system.svc"
  logPrefix: sigstorescaffolding
  privateKeyPasswordSecretName: ""
  ttlSecondsAfterFinished: 3600
  pubkeysecret: "ctlog-public-key"
  # If there's an existing private key that should be used for ctlog, specify
  # here. This is important if a key has been created and imported into TUF.
  privateSecret: ""
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
  annotations: {}
  tolerations: []
  nodeSelector: {}
  affinity: {}

trillian:
  namespace: trillian-system
  logServer:
    name: trillian-logserver
    portRPC: 8091

# Force namespace of namespaced resources
forceNamespace: ""
