{{- if and (and .Values.mysql .Values.mysql.auth) (not .Values.mysql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
{{- if and .Values.mysql.secret .Values.mysql.secret.annotations }}
  annotations:
{{ toYaml .Values.mysql.secret.annotations | indent 4 }}
{{- end }}
  labels:
{{- if and .Values.mysql.secret .Values.mysql.secret.labels }}
{{ toYaml .Values.mysql.secret.labels | indent 4 }}
{{- end }}
  name: {{ template "rekor.mysql.fullname" . }}
{{ include "rekor.namespace" . | indent 2 }}
type: Opaque
data:
  {{- if .Values.mysql.enabled -}}
  {{- if not (empty .Values.mysql.auth.rootPassword) }}
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  {{- else }}
  mysql-root-password: {{ (include "rekor.randomSecret" (dict "secretName" (include "rekor.mysql.fullname" .) "key" "mysql-root-password" "context" $)) | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if not (empty (.Values.mysql.auth).password) }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
  {{- else }}
  mysql-password: {{ (include "rekor.randomSecret" (dict "secretName" (include "rekor.mysql.fullname" .) "key" "mysql-password" "context" $)) | b64enc | quote }}
  {{- end }}
  mysql-user: {{ .Values.mysql.auth.username | b64enc | quote }}
  mysql-database:  {{ (include "mysql.database" .) | b64enc | quote }}
{{- end }}
