enabled: false
namespace:
  name: trillian-system
  create: false
serviceAccount:
  name: trillian-logserver
  annotations: {}
  create: false
spec:
  replicaCount: 1
  image: ghcr.io/sigstore/scaffolding/updatetree:v0.7.11@sha256:37ac271cbdb3c74e3146b35823e48391f24cc2c76b415a821c2f95a41dd64342
ttlSecondsAfterFinished: 3600
securityContext:
  runAsNonRoot: true
  runAsUser: 65533
args:
  treeID: ""
   # -- valid tree states are ACTIVE, FROZEN and DRAINING
  treeState: ""
annotations: {}

# Configure Trillian dependency
trillian:
  namespace: trillian-system
  adminServer: ""
  logServer:
    name: trillian-logserver
    portRPC: 8091

tolerations: []
nodeSelector: {}
affinity: {}
