enabled: false
namespace:
  name: trillian-system
  create: false
serviceAccount:
  name: trillian-logserver
  annotations: {}
  create: false
spec:
  replicaCount: 1
  image: ghcr.io/sigstore/scaffolding/updatetree:v0.7.8@sha256:08703b6f450293d7047c914765dc988a8da4f8c4cbf2b85d58bb64ba0c45ff36
ttlSecondsAfterFinished: 3600
securityContext:
  runAsNonRoot: true
  runAsUser: 65533
args:
  treeID: ""
   # -- valid tree states are ACTIVE, FROZEN and DRAINING
  treeState: ""
annotations: {}

# Configure Trillian dependency
trillian:
  namespace: trillian-system
  adminServer: ""
  logServer:
    name: trillian-logserver
    portRPC: 8091

tolerations: []
nodeSelector: {}
affinity: {}
