namespace:
  create: true
  name: sigstore-prober
serviceAccount:
  name: default
  create: false
spec:
  replicaCount: 1
  image: ghcr.io/sigstore/scaffolding/prober:v0.7.3@sha256:efd3cc7ef479cb71c8338e3978d7a82cdc30ae5e05b01c1644ac411f8bcbb9f9
  imagePullPolicy: Always
  matchLabels:
    app: sigstore-prober
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  args:
    fulcioHost: https://fulcio.sigstore.dev
    rekorHost: https://rekor.sigstore.dev
    frequency: 10
    writeProber: false
    rekorRequests: []
    fulcioRequests: []
    trustRekorAPIPublicKey: false
prometheus:
  port: 8080
tolerations: []
nodeSelector: {}
affinity: {}
