namespace:
  create: false
  name: trillian-system

imagePullSecrets: []

initContainerImage:
  curl:
    registry: docker.io
    repository: curlimages/curl
    # -- 8.9.1
    version: sha256:8addc281f0ea517409209f76832b6ddc2cabc3264feb1ebbec2a2521ffad24e4
    imagePullPolicy: IfNotPresent
  netcat:
    registry: cgr.dev
    repository: chainguard/netcat
    # -- 2024-09-03
    version: sha256:6051975a14c51b9d3b525a06004d62a4d323c08ca58e3468343095a55a42fff2
    imagePullPolicy: IfNotPresent

storageSystem:
  driver: mysql
  envCredentials: null
quotaSystem:
  driver: mysql

mysql:
  gcp:
    enabled: false
    instance: ""
    scaffoldSQLProxy:
      registry: ghcr.io
      repository: sigstore/scaffolding/cloudsqlproxy
      # -- v0.7.8 which is based on cloud-sql-proxy:2.12.0-alpine
      version: sha256:8a7539e248d38628799934e7f1c890083c90e4242e2b0feec4c352fda2574184
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
    cloudsql:
      registry: gcr.io
      repository: cloud-sql-connectors/cloud-sql-proxy:2.12.0-alpine
      # -- crane digest gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.12.0-alpine
      version: sha256:a3843521730914f074f364c5bec608319ebeb5e66da9314ba45b16cd8223547f
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
      unixDomainSocket:
        enabled: false
        path: /cloudsql
  enabled: true
  replicaCount: 1
  name: mysql
  hostname: ""
  port: 3306
  strategy:
    type: Recreate
  image:
    registry: gcr.io
    repository: trillian-opensource-ci/db_server
    pullPolicy: IfNotPresent
    # -- crane digest gcr.io/trillian-opensource-ci/db_server:v1.5.3
    version: sha256:2a685a38dd0129cceb646c232d285383f614c7e6fa51ff8f512aef78e4298461
  resources: {}
  args:
    - "--ignore-db-dir=lost+found"
  service:
    type: ClusterIP
    ports:
      - name: 3306-tcp
        port: 3306
        protocol: TCP
        targetPort: 3306
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    exec:
      command:
        - /etc/init.d/mysql
        - status
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    exec:
      command:
        - /etc/init.d/mysql
        - status
  secret:
    annotations: {}
  auth:
    username: "mysql"
    password: ""
    rootPassword: ""
    existingSecret: ""
  persistence:
    enabled: true
    annotations: {}
    storageClass: null
    size: 5Gi
    mountPath: /var/lib/mysql
    subPath: ""
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
  serviceAccount:
    create: true
    name: ""
    annotations: {}

logServer:
  enabled: true
  replicaCount: 1
  name: log-server
  portRPC: 8091
  portHTTP: 8090
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/trillian_log_server
    pullPolicy: IfNotPresent
    # -- trillian v1.6.1 (scaffolding v0.7.8)
    version: sha256:b09ad6b9f876be07baf6006afdf13402302251a373eef000cdc7a6d0c0ca584f
  nodeSelector: {}
  tolerations: []
  affinity: {}
  service:
    type: ClusterIP
    ports:
      - name: 8091-tcp
        port: 8091
        protocol: TCP
        targetPort: 8091
      - name: 8090-tcp
        port: 8090
        protocol: TCP
        targetPort: 8090
  livenessProbe: {}
  readinessProbe: {}
  resources: {}
  extraArgs: []
  serviceAccount:
    create: true
    name: ""
    annotations: {}

logSigner:
  enabled: true
  replicaCount: 1
  name: log-signer
  forceMaster: true
  portRPC: 8091
  portHTTP: 8090
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/trillian_log_signer
    pullPolicy: IfNotPresent
    # -- trillian v1.6.1 (scaffolding v0.7.8)
    version: sha256:9ddaf6c45cab0177db6e599d8bde12a46e1913181f4a6942096655e0435d0212
  nodeSelector: {}
  tolerations: []
  affinity: {}
  service:
    type: ClusterIP
    ports:
      - name: 8091-tcp
        port: 8091
        protocol: TCP
        targetPort: 8091
  livenessProbe: {}
  readinessProbe: {}
  resources: {}
  extraArgs: []
  serviceAccount:
    create: true
    name: ""
    annotations: {}

createdb:
  enabled: true
  dbname: trillian
  ttlSecondsAfterFinished: 3600
  name: createdb
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createdb
    pullPolicy: IfNotPresent
    # -- v0.7.8
    version: sha256:674760d4000f151b768843e6d7f671b8e3ada037736e312b4939b3a48abd6066
  serviceAccount:
    create: false
    name: ""
    annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Force namespace of namespaced resources
forceNamespace: ""
